spring.application.name=preownedsales

spring.datasource.url=jdbc:sqlserver://localhost;databaseName=PreOwnedSalesDB;encrypt=false;trustServerCertificate=true;instanceName=SQLEXPRESS
spring.datasource.username=sa
spring.datasource.password=822631
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
